const CUSTOMERS = [
  {
    id: 0,
    firstName: "Luann",
    lastName: "Baird",
    email: "bairdwaller@isoplex.com",
  },
  {
    id: 1,
    firstName: "Jewell",
    lastName: "Christensen",
    email: "christensenwaller@isoplex.com",
  },
  {
    id: 2,
    firstName: "Ray",
    lastName: "Santiago",
    email: "santiagowaller@isoplex.com",
  },
  {
    id: 3,
    firstName: "Shepard",
    lastName: "Franco",
    email: "francowaller@isoplex.com",
  },
  {
    id: 4,
    firstName: "Lina",
    lastName: "Ruth",
    email: "ruthwaller@isoplex.com",
  },
  {
    id: 5,
    firstName: "Mcpherson",
    lastName: "Judith",
    email: "judithwaller@isoplex.com",
  },
  {
    id: 6,
    firstName: "Rodgers",
    lastName: "Keller",
    email: "kellerwaller@isoplex.com",
  },
  {
    id: 7,
    firstName: "Clay",
    lastName: "Augusta",
    email: "augustawaller@isoplex.com",
  },
  {
    id: 8,
    firstName: "Melinda",
    lastName: "Leta",
    email: "letawaller@isoplex.com",
  },
  {
    id: 9,
    firstName: "Lilly",
    lastName: "Rosemary",
    email: "rosemarywaller@isoplex.com",
  },
  {
    id: 10,
    firstName: "Stein",
    lastName: "Rebekah",
    email: "rebekahwaller@isoplex.com",
  },
  {
    id: 11,
    firstName: "Erika",
    lastName: "Frances",
    email: "franceswaller@isoplex.com",
  },
  {
    id: 12,
    firstName: "Butler",
    lastName: "Deana",
    email: "deanawaller@isoplex.com",
  },
  {
    id: 13,
    firstName: "Faulkner",
    lastName: "Katharine",
    email: "katharinewaller@isoplex.com",
  },
  {
    id: 14,
    firstName: "Lillie",
    lastName: "Whitehead",
    email: "whiteheadwaller@isoplex.com",
  },
  {
    id: 15,
    firstName: "Hogan",
    lastName: "Maryanne",
    email: "maryannewaller@isoplex.com",
  },
  {
    id: 16,
    firstName: "Cochran",
    lastName: "Harriett",
    email: "harriettwaller@isoplex.com",
  },
  {
    id: 17,
    firstName: "Nola",
    lastName: "Charlene",
    email: "charlenewaller@isoplex.com",
  },
  {
    id: 18,
    firstName: "Nellie",
    lastName: "Barbra",
    email: "barbrawaller@isoplex.com",
  },
  {
    id: 19,
    firstName: "Fields",
    lastName: "Higgins",
    email: "higginswaller@isoplex.com",
  },
  {
    id: 20,
    firstName: "Dodson",
    lastName: "Hodge",
    email: "hodgewaller@isoplex.com",
  },
  {
    id: 21,
    firstName: "Burgess",
    lastName: "Mcdonald",
    email: "mcdonaldwaller@isoplex.com",
  },
  {
    id: 22,
    firstName: "Green",
    lastName: "Dejesus",
    email: "dejesuswaller@isoplex.com",
  },
  {
    id: 23,
    firstName: "Laura",
    lastName: "Brandi",
    email: "brandiwaller@isoplex.com",
  },
  {
    id: 24,
    firstName: "Mariana",
    lastName: "Guadalupe",
    email: "guadalupewaller@isoplex.com",
  },
  {
    id: 25,
    firstName: "Stone",
    lastName: "Natasha",
    email: "natashawaller@isoplex.com",
  },
  {
    id: 26,
    firstName: "Mccormick",
    lastName: "Lynne",
    email: "lynnewaller@isoplex.com",
  },
  {
    id: 27,
    firstName: "Hooper",
    lastName: "Sargent",
    email: "sargentwaller@isoplex.com",
  },
  {
    id: 28,
    firstName: "Carolyn",
    lastName: "Tanisha",
    email: "tanishawaller@isoplex.com",
  },
  {
    id: 29,
    firstName: "Conner",
    lastName: "Branch",
    email: "branchwaller@isoplex.com",
  },
  {
    id: 30,
    firstName: "Carly",
    lastName: "Eileen",
    email: "eileenwaller@isoplex.com",
  },
  {
    id: 31,
    firstName: "Good",
    lastName: "Riddle",
    email: "riddlewaller@isoplex.com",
  },
  {
    id: 32,
    firstName: "Kathie",
    lastName: "Hudson",
    email: "hudsonwaller@isoplex.com",
  },
  {
    id: 33,
    firstName: "Collins",
    lastName: "Roberson",
    email: "robersonwaller@isoplex.com",
  },
  {
    id: 34,
    firstName: "Pamela",
    lastName: "Jaime",
    email: "jaimewaller@isoplex.com",
  },
  {
    id: 35,
    firstName: "Felecia",
    lastName: "Rosales",
    email: "rosaleswaller@isoplex.com",
  },
  {
    id: 36,
    firstName: "Nolan",
    lastName: "Larsen",
    email: "larsenwaller@isoplex.com",
  },
  {
    id: 37,
    firstName: "Avery",
    lastName: "Lily",
    email: "lilywaller@isoplex.com",
  },
  {
    id: 38,
    firstName: "Ashlee",
    lastName: "Elisa",
    email: "elisawaller@isoplex.com",
  },
  {
    id: 39,
    firstName: "Mae",
    lastName: "Sherry",
    email: "sherrywaller@isoplex.com",
  },
  {
    id: 40,
    firstName: "Marian",
    lastName: "Delacruz",
    email: "delacruzwaller@isoplex.com",
  },
  {
    id: 41,
    firstName: "Jean",
    lastName: "Blanchard",
    email: "blanchardwaller@isoplex.com",
  },
  {
    id: 42,
    firstName: "Austin",
    lastName: "Steele",
    email: "steelewaller@isoplex.com",
  },
  {
    id: 43,
    firstName: "Wright",
    lastName: "Michele",
    email: "michelewaller@isoplex.com",
  },
  {
    id: 44,
    firstName: "Alston",
    lastName: "Burris",
    email: "burriswaller@isoplex.com",
  },
  {
    id: 45,
    firstName: "Powers",
    lastName: "Jacquelyn",
    email: "jacquelynwaller@isoplex.com",
  },
  {
    id: 46,
    firstName: "Perez",
    lastName: "Burke",
    email: "burkewaller@isoplex.com",
  },
  {
    id: 47,
    firstName: "Autumn",
    lastName: "Petty",
    email: "pettywaller@isoplex.com",
  },
  {
    id: 48,
    firstName: "Cox",
    lastName: "Hendrix",
    email: "hendrixwaller@isoplex.com",
  },
  {
    id: 49,
    firstName: "Aurelia",
    lastName: "Bridget",
    email: "bridgetwaller@isoplex.com",
  },
  {
    id: 50,
    firstName: "Woods",
    lastName: "Fischer",
    email: "fischerwaller@isoplex.com",
  },
  {
    id: 51,
    firstName: "Blanca",
    lastName: "Kramer",
    email: "kramerwaller@isoplex.com",
  },
  {
    id: 52,
    firstName: "Randolph",
    lastName: "Alyssa",
    email: "alyssawaller@isoplex.com",
  },
  {
    id: 53,
    firstName: "Vaughn",
    lastName: "Moon",
    email: "moonwaller@isoplex.com",
  },
  {
    id: 54,
    firstName: "Marjorie",
    lastName: "Davidson",
    email: "davidsonwaller@isoplex.com",
  },
  {
    id: 55,
    firstName: "Terry",
    lastName: "Tricia",
    email: "triciawaller@isoplex.com",
  },
  {
    id: 56,
    firstName: "Ferguson",
    lastName: "Peck",
    email: "peckwaller@isoplex.com",
  },
  {
    id: 57,
    firstName: "Beth",
    lastName: "Rocha",
    email: "rochawaller@isoplex.com",
  },
  {
    id: 58,
    firstName: "Carpenter",
    lastName: "Charity",
    email: "charitywaller@isoplex.com",
  },
  {
    id: 59,
    firstName: "Olga",
    lastName: "Lakisha",
    email: "lakishawaller@isoplex.com",
  },
  {
    id: 60,
    firstName: "Torres",
    lastName: "Hyde",
    email: "hydewaller@isoplex.com",
  },
  {
    id: 61,
    firstName: "Spencer",
    lastName: "Mccullough",
    email: "mcculloughwaller@isoplex.com",
  },
  {
    id: 62,
    firstName: "Norris",
    lastName: "Huber",
    email: "huberwaller@isoplex.com",
  },
  {
    id: 63,
    firstName: "Stella",
    lastName: "Henson",
    email: "hensonwaller@isoplex.com",
  },
];

export default CUSTOMERS;
